### ISSUE TITLE
Audio gets more and more choppy in retakes

### ISSUE THREAD

**Issue by Metapyziks** [Facepunch/sbox-hc1#156]
Both sound effects and player voices start stuttering, getting worse over time.

Reconnecting fixes it.
```[tasklist]
### Tasks
- [x] Test swapping teams, then swapping again one update later
- [x] Test swapping when players are dead
- [x] Add logging for the next test
```

**Comment by Metapyziks** [comment]
Cleaned up respawning a bit, let's see if that helps.

**Comment by Metapyziks** [comment]
Still happening in retakes, but only when teams switch.
