### ISSUE TITLE
Bomb Defuse Mode

### ISSUE THREAD

**Issue by Metapyziks** [Facepunch/sbox-hc1#22]
```[tasklist]
### Tasks
- [x] C4 Weapon
- [x] Allocate to one Terrorist
- [x] Planting C4
- [x] Define bomb sites
- [x] Immobilise player while planting
- [x] Defusing C4
- [x] When planted, disable round timer
- [x] Exploded win condition
- [x] Defused win condition
```
