### ISSUE TITLE
Equipment

### ISSUE THREAD

**Issue by Metapyziks** [Facepunch/sbox-hc1#3]
Feel free to spin these out into separate issues:

```[tasklist]
### Armor
- [x] Kevlar
- [x] Helmet
```

```[tasklist]
### Weapons
- [x] Knife
- [x] USP
- [x] MP5
- [x] M4A1
- [ ] https://github.com/Facepunch/sbox-hc1/issues/25
- [ ] https://github.com/Facepunch/sbox-hc1/issues/39
```

```[tasklist]
### Grenades
- [x] HE Grenade
- [ ] Smoke Grenade
- [ ] Flashbang
- [ ] Molotov?
```

```[tasklist]
### Tasks for Art \[WHITEBOX]
- [ ] https://github.com/Facepunch/sbox-hc1/issues/11
- [ ] https://github.com/Facepunch/sbox-hc1/issues/12
- [ ] https://github.com/Facepunch/sbox-hc1/issues/13
- [ ] https://github.com/Facepunch/sbox-hc1/issues/14
- [ ] ART - Terrorist Bomb (C4)
```

**Comment by DevulTj** [comment]
Gonna close this, and stick to the individual tasks for grenades.
