### ISSUE TITLE
Last Day

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#38]
```[tasklist]
### Pains
- [ ] #36
- [ ] #34
- [x] Weapon pickups are inconsistent and annoying
- [x] FixedUpdate is taking a good chunk chunk of frame time, let's find out where.
- [x] Go through all of our UI, look at ways we can cut down on rebuilding some panels, I'm sure we're losing some frame time from this.
- [x] Let's look at our movement code, try to cut down on what's running on remote clients if possible
- [x] Spectating - after respawning, we can sometimes see our own skins
```

```[tasklist]
### Tasks
- [x] Implement ability to buy kevlar, helmet, defuse kits.
- [x] Finish implementation of the M700 sniper rifle. No animations required, just #8, and balance.
- [ ] #37
```

Playtest at 4:30, as usual. Goal for today is to have a clean, minimally buggy experience.
