### ISSUE TITLE
TDM

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#49]
Let's add a deathmatch/team deathmatch game type, no round flow, less waiting around, just fun, no economy, loadout is saved
```[tasklist]
### Tasks
- [x] Control auto-respawning with game rule
- [x] Frags increment team score
- [x] Unlimited / hidden money
- [x] Buy anywhere
- [x] Save loadout per player
- [x] Spawn protection?
```

```[tasklist]
### Playtest Feedback
- [x] Can shoot when dead
- [ ] https://github.com/Facepunch/sbox-hc1/issues/60
- [x] Make it more obvious that you're alive after respawn
- [ ] Spawn protection doesn't always disable when moving
- [x] Make sure players don't respawn near / in LoS of an enemy
- [x] Toast on game end
```

**Comment by Metapyziks** [comment]
Working on a basic way for maps to specify which game modes they support. I'm thinking just look for GameMode components in the scene, and only enable one of them when the game starts.

**Comment by DevulTj** [comment]
> Working on a basic way for maps to specify which game modes they support. I'm thinking just look for GameMode components in the scene, and only enable one of them when the game starts.

yeah, i think this'll be good for the main menu system, where you can pick gamemode/maps there

**Comment by Metapyziks** [comment]
Alright, should be ready for a play test.

**Comment by DevulTj** [comment]
Great stuff on this btw
